# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dynamic_assets}
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Davis"]
  s.date = %q{2011-06-08}
  s.description = %q{Allow your Rails 3 app to package and process your CSS and JS assets on the fly.}
  s.email = %q{davis@coaster.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/assets_controller.rb",
    "app/helpers/dynamic_assets_helpers.rb",
    "config/routes.rb",
    "lib/dynamic_assets.rb",
    "lib/dynamic_assets/config.rb",
    "lib/dynamic_assets/controller.rb",
    "lib/dynamic_assets/core_extensions.rb",
    "lib/dynamic_assets/cssmin.rb",
    "lib/dynamic_assets/engine.rb",
    "lib/dynamic_assets/manager.rb",
    "lib/dynamic_assets/reference.rb",
    "lib/dynamic_assets/reference/javascript_reference.rb",
    "lib/dynamic_assets/reference/stylesheet_reference.rb",
    "lib/dynamic_assets/view_context.rb"
  ]
  s.homepage = %q{http://github.com/davisre/dynamic_assets}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Allow your Rails 3 app to package and process your CSS and JS assets on the fly.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0"])
      s.add_runtime_dependency(%q<jsmin>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<capybara>, ["= 1.0.0.beta1"])
      s.add_development_dependency(%q<rspec-rails>, ["= 2.6.0.rc6"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0"])
      s.add_dependency(%q<jsmin>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<capybara>, ["= 1.0.0.beta1"])
      s.add_dependency(%q<rspec-rails>, ["= 2.6.0.rc6"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0"])
    s.add_dependency(%q<jsmin>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<capybara>, ["= 1.0.0.beta1"])
    s.add_dependency(%q<rspec-rails>, ["= 2.6.0.rc6"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

